🚸 Provide a better message for AccessDenied to opening COM port
Summary: Catch SerialExceptions and re-raise them, possibly with a wrapper to provide a better message if access was denied to the COM port. This is most commonly caused by another program holding the port (such as VCS, ROBOTC, or firmware utilities)

Test Plan:
- [X] Run `prosv5 v5 status` with the V5 firmware utility open and see new exception with status message
```
PS C:\Users\Elliot> prosv5 v5 status
ERROR - pros.cli.main:main - could not open port 'COM7'. try closing any other VEX IDEs such as ROBOTC, VCS, or firmware utilities
  File "C:\Users\Elliot\AppData\Local\Programs\Python\Python36\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
pros.serial.ports.exceptions.ConnectionRefusedException: could not open port 'COM7'. try closing any other VEX IDEs such as ROBOTC, VCS, or firmware utilities
We detected something went wrong! Would you like to send a bug report to the PROS Development team? [Y/n]: n
```

Reviewers: O3 The Q Continuum, brookea

Reviewed By: O3 The Q Continuum, brookea

Subscribers: brookea

Tags: #zorp

Maniphest Tasks: T683

Differential Revision: https://phabricator.purduesigbots.com/D224